/* ============================================================
   SISTEMA DE PROGRAMAS SOCIAIS
   PostgreSQL 12+
   Modelo com dados pessoais, identificáveis e sensíveis (LGPD)
   Utiliza schema próprio e colunas IDENTITY.
   ============================================================ */

CREATE SCHEMA IF NOT EXISTS social;

SET search_path TO social;

-- ============================================================
-- PESSOA
-- ============================================================

CREATE TABLE pessoa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_completo VARCHAR(200) NOT NULL,
    cpf CHAR(11) NOT NULL UNIQUE,
    data_nascimento DATE NOT NULL,
    sexo_biologico VARCHAR(30),
    orientacao_sexual VARCHAR(50),
    identidade_genero VARCHAR(50),
    nome_social VARCHAR(200),
    estado_civil VARCHAR(50),
    renda_familiar_mensal NUMERIC(15,2),
    email VARCHAR(200),
    telefone VARCHAR(30),
    data_cadastro TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE pessoa IS
'Cadastro principal de cidadãos participantes de programas sociais';

COMMENT ON COLUMN pessoa.id IS
'Identificador único da pessoa';

COMMENT ON COLUMN pessoa.nome_completo IS
'Nome completo da pessoa | CLASSIFICACAO=LGPD_IDENTIFICAVEL';

COMMENT ON COLUMN pessoa.cpf IS
'CPF da pessoa | CLASSIFICACAO=LGPD_IDENTIFICAVEL';

COMMENT ON COLUMN pessoa.data_nascimento IS
'Data de nascimento da pessoa | CLASSIFICACAO=LGPD_PESSOAL';

COMMENT ON COLUMN pessoa.sexo_biologico IS
'Sexo biologico informado pela pessoa | CLASSIFICACAO=LGPD_SENSIVEL';

COMMENT ON COLUMN pessoa.orientacao_sexual IS
'Orientacao sexual declarada | CLASSIFICACAO=LGPD_SENSIVEL';

COMMENT ON COLUMN pessoa.identidade_genero IS
'Identidade de genero declarada | CLASSIFICACAO=LGPD_SENSIVEL';

COMMENT ON COLUMN pessoa.nome_social IS
'Nome social utilizado pela pessoa | CLASSIFICACAO=LGPD_IDENTIFICAVEL';

COMMENT ON COLUMN pessoa.estado_civil IS
'Estado civil da pessoa | CLASSIFICACAO=LGPD_PESSOAL';

COMMENT ON COLUMN pessoa.renda_familiar_mensal IS
'Renda familiar mensal declarada | CLASSIFICACAO=LGPD_PESSOAL';

COMMENT ON COLUMN pessoa.email IS
'Endereco de email para contato | CLASSIFICACAO=LGPD_IDENTIFICAVEL';

COMMENT ON COLUMN pessoa.telefone IS
'Telefone para contato | CLASSIFICACAO=LGPD_IDENTIFICAVEL';

COMMENT ON COLUMN pessoa.data_cadastro IS
'Data de cadastro da pessoa no sistema';

-- ============================================================
-- ENDERECO
-- ============================================================

CREATE TABLE endereco (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pessoa BIGINT NOT NULL,
    tipo_endereco VARCHAR(20) NOT NULL,
    logradouro VARCHAR(200) NOT NULL,
    numero VARCHAR(20),
    complemento VARCHAR(200),
    bairro VARCHAR(100),
    cidade VARCHAR(100) NOT NULL,
    uf CHAR(2) NOT NULL,
    cep CHAR(8),

    CONSTRAINT fk_endereco_pessoa
        FOREIGN KEY (id_pessoa)
        REFERENCES pessoa(id)
);

COMMENT ON TABLE endereco IS
'Enderecos cadastrados para uma pessoa';

COMMENT ON COLUMN endereco.id IS
'Identificador unico do endereco';

COMMENT ON COLUMN endereco.id_pessoa IS
'Pessoa proprietaria do endereco';

COMMENT ON COLUMN endereco.tipo_endereco IS
'Tipo do endereco';

COMMENT ON COLUMN endereco.logradouro IS
'Nome do logradouro | CLASSIFICACAO=LGPD_IDENTIFICAVEL';

COMMENT ON COLUMN endereco.numero IS
'Numero do imovel | CLASSIFICACAO=LGPD_IDENTIFICAVEL';

COMMENT ON COLUMN endereco.complemento IS
'Complemento do endereco | CLASSIFICACAO=LGPD_IDENTIFICAVEL';

COMMENT ON COLUMN endereco.bairro IS
'Bairro do endereco | CLASSIFICACAO=LGPD_PESSOAL';

COMMENT ON COLUMN endereco.cidade IS
'Cidade do endereco | CLASSIFICACAO=LGPD_PESSOAL';

COMMENT ON COLUMN endereco.uf IS
'Estado do endereco | CLASSIFICACAO=LGPD_PESSOAL';

COMMENT ON COLUMN endereco.cep IS
'CEP do endereco | CLASSIFICACAO=LGPD_PESSOAL';

-- ============================================================
-- ESCOLARIDADE
-- ============================================================

CREATE TABLE escolaridade (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(100) NOT NULL UNIQUE
);

COMMENT ON TABLE escolaridade IS
'Catalogo de niveis de escolaridade';

COMMENT ON COLUMN escolaridade.id IS
'Identificador da escolaridade';

COMMENT ON COLUMN escolaridade.descricao IS
'Descricao do nivel de escolaridade';

-- ============================================================
-- FORMACAO
-- ============================================================

CREATE TABLE formacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(150) NOT NULL,
    area_conhecimento VARCHAR(150) NOT NULL
);

COMMENT ON TABLE formacao IS
'Catalogo de formacoes academicas';

COMMENT ON COLUMN formacao.id IS
'Identificador da formacao';

COMMENT ON COLUMN formacao.descricao IS
'Descricao da formacao academica';

COMMENT ON COLUMN formacao.area_conhecimento IS
'Area de conhecimento da formacao';

-- ============================================================
-- PROFISSAO
-- ============================================================

CREATE TABLE profissao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(150) NOT NULL UNIQUE
);

COMMENT ON TABLE profissao IS
'Catalogo de profissoes';

COMMENT ON COLUMN profissao.id IS
'Identificador da profissao';

COMMENT ON COLUMN profissao.descricao IS
'Descricao da profissao';

-- ============================================================
-- PROGRAMA SOCIAL
-- ============================================================

CREATE TABLE programa_social (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(200) NOT NULL UNIQUE,
    descricao VARCHAR(500)
);

COMMENT ON TABLE programa_social IS
'Programas sociais disponiveis';

COMMENT ON COLUMN programa_social.id IS
'Identificador do programa social';

COMMENT ON COLUMN programa_social.nome IS
'Nome do programa social';

COMMENT ON COLUMN programa_social.descricao IS
'Descricao do programa social';

-- ============================================================
-- PESSOA_ESCOLARIDADE
-- CHAVE COMPOSTA
-- ============================================================

CREATE TABLE pessoa_escolaridade (
    id_pessoa BIGINT NOT NULL,
    id_escolaridade BIGINT NOT NULL,
    data_inicio DATE,
    data_conclusao DATE,

    CONSTRAINT pk_pessoa_escolaridade
        PRIMARY KEY (
            id_pessoa,
            id_escolaridade
        ),

    CONSTRAINT fk_pessoa_escolaridade_pessoa
        FOREIGN KEY (id_pessoa)
        REFERENCES pessoa(id),

    CONSTRAINT fk_pessoa_escolaridade_escolaridade
        FOREIGN KEY (id_escolaridade)
        REFERENCES escolaridade(id)
);

COMMENT ON TABLE pessoa_escolaridade IS
'Historico de escolaridade da pessoa';

COMMENT ON COLUMN pessoa_escolaridade.id_pessoa IS
'Pessoa associada ao nivel de escolaridade';

COMMENT ON COLUMN pessoa_escolaridade.id_escolaridade IS
'Escolaridade associada a pessoa';

COMMENT ON COLUMN pessoa_escolaridade.data_inicio IS
'Data de inicio da escolaridade';

COMMENT ON COLUMN pessoa_escolaridade.data_conclusao IS
'Data de conclusao da escolaridade';

-- ============================================================
-- PESSOA_FORMACAO
-- CHAVE COMPOSTA
-- ============================================================

CREATE TABLE pessoa_formacao (
    id_pessoa BIGINT NOT NULL,
    id_formacao BIGINT NOT NULL,
    instituicao VARCHAR(200),
    ano_conclusao INTEGER,

    CONSTRAINT pk_pessoa_formacao
        PRIMARY KEY (
            id_pessoa,
            id_formacao
        ),

    CONSTRAINT fk_pessoa_formacao_pessoa
        FOREIGN KEY (id_pessoa)
        REFERENCES pessoa(id),

    CONSTRAINT fk_pessoa_formacao_formacao
        FOREIGN KEY (id_formacao)
        REFERENCES formacao(id)
);

COMMENT ON TABLE pessoa_formacao IS
'Formacoes academicas obtidas pela pessoa';

COMMENT ON COLUMN pessoa_formacao.id_pessoa IS
'Pessoa associada a formacao';

COMMENT ON COLUMN pessoa_formacao.id_formacao IS
'Formacao associada a pessoa';

COMMENT ON COLUMN pessoa_formacao.instituicao IS
'Instituicao de ensino frequentada | CLASSIFICACAO=LGPD_PESSOAL';

COMMENT ON COLUMN pessoa_formacao.ano_conclusao IS
'Ano de conclusao da formacao';

-- ============================================================
-- PESSOA_PROFISSAO
-- CHAVE COMPOSTA
-- ============================================================

CREATE TABLE pessoa_profissao (
    id_pessoa BIGINT NOT NULL,
    id_profissao BIGINT NOT NULL,
    principal BOOLEAN NOT NULL DEFAULT FALSE,
    renda_mensal NUMERIC(15,2),

    CONSTRAINT pk_pessoa_profissao
        PRIMARY KEY (
            id_pessoa,
            id_profissao
        ),

    CONSTRAINT fk_pessoa_profissao_pessoa
        FOREIGN KEY (id_pessoa)
        REFERENCES pessoa(id),

    CONSTRAINT fk_pessoa_profissao_profissao
        FOREIGN KEY (id_profissao)
        REFERENCES profissao(id)
);

COMMENT ON TABLE pessoa_profissao IS
'Profissoes exercidas pela pessoa';

COMMENT ON COLUMN pessoa_profissao.id_pessoa IS
'Pessoa associada a profissao';

COMMENT ON COLUMN pessoa_profissao.id_profissao IS
'Profissao exercida pela pessoa';

COMMENT ON COLUMN pessoa_profissao.principal IS
'Indica se a profissao e a principal';

COMMENT ON COLUMN pessoa_profissao.renda_mensal IS
'Renda mensal da atividade profissional | CLASSIFICACAO=LGPD_PESSOAL';

-- ============================================================
-- PESSOA_PROGRAMA_SOCIAL
-- CHAVE COMPOSTA
-- ============================================================

CREATE TABLE pessoa_programa_social (
    id_pessoa BIGINT NOT NULL,
    id_programa_social BIGINT NOT NULL,
    data_adesao DATE NOT NULL,
    situacao VARCHAR(30) NOT NULL,

    CONSTRAINT pk_pessoa_programa_social
        PRIMARY KEY (
            id_pessoa,
            id_programa_social
        ),

    CONSTRAINT fk_pessoa_programa_social_pessoa
        FOREIGN KEY (id_pessoa)
        REFERENCES pessoa(id),

    CONSTRAINT fk_pessoa_programa_social_programa
        FOREIGN KEY (id_programa_social)
        REFERENCES programa_social(id)
);

COMMENT ON TABLE pessoa_programa_social IS
'Participacao da pessoa em programas sociais';

COMMENT ON COLUMN pessoa_programa_social.id_pessoa IS
'Pessoa participante do programa social';

COMMENT ON COLUMN pessoa_programa_social.id_programa_social IS
'Programa social associado';

COMMENT ON COLUMN pessoa_programa_social.data_adesao IS
'Data de adesao da pessoa ao programa';

COMMENT ON COLUMN pessoa_programa_social.situacao IS
'Situacao da participacao da pessoa no programa';

-- ============================================================
-- INDICES
-- ============================================================

CREATE INDEX idx_pessoa_cpf
    ON pessoa(cpf);

CREATE INDEX idx_pessoa_nome
    ON pessoa(nome_completo);

CREATE INDEX idx_endereco_id_pessoa
    ON endereco(id_pessoa);

CREATE INDEX idx_pessoa_programa_social_pessoa
    ON pessoa_programa_social(id_pessoa);

CREATE INDEX idx_pessoa_programa_social_programa
    ON pessoa_programa_social(id_programa_social);

CREATE INDEX idx_pessoa_profissao_pessoa
    ON pessoa_profissao(id_pessoa);

CREATE INDEX idx_pessoa_formacao_pessoa
    ON pessoa_formacao(id_pessoa);

CREATE INDEX idx_pessoa_escolaridade_pessoa
    ON pessoa_escolaridade(id_pessoa);