-- ============================================================
-- SISTEMA DE PROGRAMAS SOCIAIS
-- IBM Db2 LUW
-- Modelo com dados pessoais, identificáveis e sensíveis (LGPD)
-- ============================================================

CREATE SCHEMA SOCIAL;

SET CURRENT SCHEMA SOCIAL;

-- ============================================================
-- PESSOA
-- ============================================================

CREATE TABLE PESSOA (
    ID BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    NOME_COMPLETO VARCHAR(200) NOT NULL,
    CPF CHAR(11) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    SEXO_BIOLOGICO VARCHAR(30),
    ORIENTACAO_SEXUAL VARCHAR(50),
    IDENTIDADE_GENERO VARCHAR(50),
    NOME_SOCIAL VARCHAR(200),
    ESTADO_CIVIL VARCHAR(50),
    RENDA_FAMILIAR_MENSAL DECIMAL(15,2),
    EMAIL VARCHAR(200),
    TELEFONE VARCHAR(30),

    DATA_CADASTRO TIMESTAMP
        NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT UK_PESSOA_CPF
        UNIQUE (CPF)
);

-- ============================================================
-- ENDERECO
-- ============================================================

CREATE TABLE ENDERECO (
    ID BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    ID_PESSOA BIGINT NOT NULL,

    TIPO_ENDERECO VARCHAR(20) NOT NULL,
    LOGRADOURO VARCHAR(200) NOT NULL,
    NUMERO VARCHAR(20),
    COMPLEMENTO VARCHAR(200),
    BAIRRO VARCHAR(100),
    CIDADE VARCHAR(100) NOT NULL,
    UF CHAR(2) NOT NULL,
    CEP CHAR(8),

    CONSTRAINT FK_ENDERECO_PESSOA
        FOREIGN KEY (ID_PESSOA)
        REFERENCES PESSOA (ID)
);

-- ============================================================
-- ESCOLARIDADE
-- ============================================================

CREATE TABLE ESCOLARIDADE (
    ID BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    DESCRICAO VARCHAR(100) NOT NULL,

    CONSTRAINT UK_ESCOLARIDADE_DESCRICAO
        UNIQUE (DESCRICAO)
);

-- ============================================================
-- FORMACAO
-- ============================================================

CREATE TABLE FORMACAO (
    ID BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    DESCRICAO VARCHAR(150) NOT NULL,
    AREA_CONHECIMENTO VARCHAR(150) NOT NULL
);

-- ============================================================
-- PROFISSAO
-- ============================================================

CREATE TABLE PROFISSAO (
    ID BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    DESCRICAO VARCHAR(150) NOT NULL,

    CONSTRAINT UK_PROFISSAO_DESCRICAO
        UNIQUE (DESCRICAO)
);

-- ============================================================
-- PROGRAMA SOCIAL
-- ============================================================

CREATE TABLE PROGRAMA_SOCIAL (
    ID BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    NOME VARCHAR(200) NOT NULL,
    DESCRICAO VARCHAR(500),

    CONSTRAINT UK_PROGRAMA_SOCIAL_NOME
        UNIQUE (NOME)
);

-- ============================================================
-- PESSOA_ESCOLARIDADE
-- ============================================================

CREATE TABLE PESSOA_ESCOLARIDADE (

    ID_PESSOA BIGINT NOT NULL,
    ID_ESCOLARIDADE BIGINT NOT NULL,

    DATA_INICIO DATE,
    DATA_CONCLUSAO DATE,

    CONSTRAINT PK_PESSOA_ESCOLARIDADE
        PRIMARY KEY (
            ID_PESSOA,
            ID_ESCOLARIDADE
        ),

    CONSTRAINT FK_PESC_PESSOA
        FOREIGN KEY (ID_PESSOA)
        REFERENCES PESSOA(ID),

    CONSTRAINT FK_PESC_ESCOLARIDADE
        FOREIGN KEY (ID_ESCOLARIDADE)
        REFERENCES ESCOLARIDADE(ID)
);

-- ============================================================
-- PESSOA_FORMACAO
-- ============================================================

CREATE TABLE PESSOA_FORMACAO (

    ID_PESSOA BIGINT NOT NULL,
    ID_FORMACAO BIGINT NOT NULL,

    INSTITUICAO VARCHAR(200),
    ANO_CONCLUSAO INTEGER,

    CONSTRAINT PK_PESSOA_FORMACAO
        PRIMARY KEY (
            ID_PESSOA,
            ID_FORMACAO
        ),

    CONSTRAINT FK_PFORM_PESSOA
        FOREIGN KEY (ID_PESSOA)
        REFERENCES PESSOA(ID),

    CONSTRAINT FK_PFORM_FORMACAO
        FOREIGN KEY (ID_FORMACAO)
        REFERENCES FORMACAO(ID)
);

-- ============================================================
-- PESSOA_PROFISSAO
-- ============================================================

CREATE TABLE PESSOA_PROFISSAO (

    ID_PESSOA BIGINT NOT NULL,
    ID_PROFISSAO BIGINT NOT NULL,

    PRINCIPAL SMALLINT
        NOT NULL
        DEFAULT 0,

    RENDA_MENSAL DECIMAL(15,2),

    CONSTRAINT PK_PESSOA_PROFISSAO
        PRIMARY KEY (
            ID_PESSOA,
            ID_PROFISSAO
        ),

    CONSTRAINT FK_PPROF_PESSOA
        FOREIGN KEY (ID_PESSOA)
        REFERENCES PESSOA(ID),

    CONSTRAINT FK_PPROF_PROFISSAO
        FOREIGN KEY (ID_PROFISSAO)
        REFERENCES PROFISSAO(ID),

    CONSTRAINT CK_PPROF_PRINCIPAL
        CHECK (PRINCIPAL IN (0,1))
);

-- ============================================================
-- PESSOA_PROGRAMA_SOCIAL
-- ============================================================

CREATE TABLE PESSOA_PROGRAMA_SOCIAL (

    ID_PESSOA BIGINT NOT NULL,
    ID_PROGRAMA_SOCIAL BIGINT NOT NULL,

    DATA_ADESAO DATE NOT NULL,
    SITUACAO VARCHAR(30) NOT NULL,

    CONSTRAINT PK_PESSOA_PROGRAMA_SOCIAL
        PRIMARY KEY (
            ID_PESSOA,
            ID_PROGRAMA_SOCIAL
        ),

    CONSTRAINT FK_PPGR_PESSOA
        FOREIGN KEY (ID_PESSOA)
        REFERENCES PESSOA(ID),

    CONSTRAINT FK_PPGR_PROGRAMA
        FOREIGN KEY (ID_PROGRAMA_SOCIAL)
        REFERENCES PROGRAMA_SOCIAL(ID)
);

-- ============================================================
-- COMENTARIOS DE TABELAS
-- ============================================================

COMMENT ON TABLE PESSOA IS
'Cadastro principal de cidadãos participantes de programas sociais';

COMMENT ON TABLE ENDERECO IS
'Enderecos cadastrados para uma pessoa';

COMMENT ON TABLE ESCOLARIDADE IS
'Catalogo de niveis de escolaridade';

COMMENT ON TABLE FORMACAO IS
'Catalogo de formacoes academicas';

COMMENT ON TABLE PROFISSAO IS
'Catalogo de profissoes';

COMMENT ON TABLE PROGRAMA_SOCIAL IS
'Programas sociais disponiveis';

COMMENT ON TABLE PESSOA_ESCOLARIDADE IS
'Historico de escolaridade da pessoa';

COMMENT ON TABLE PESSOA_FORMACAO IS
'Formacoes academicas obtidas pela pessoa';

COMMENT ON TABLE PESSOA_PROFISSAO IS
'Profissoes exercidas pela pessoa';

COMMENT ON TABLE PESSOA_PROGRAMA_SOCIAL IS
'Participacao da pessoa em programas sociais';

-- ============================================================
-- COMENTARIOS DE COLUNAS (LGPD)
-- ============================================================

COMMENT ON COLUMN PESSOA.NOME_COMPLETO IS
'Nome completo da pessoa | CLASSIFICACAO=LGPD_IDENTIFICAVEL';

COMMENT ON COLUMN PESSOA.CPF IS
'CPF da pessoa | CLASSIFICACAO=LGPD_IDENTIFICAVEL';

COMMENT ON COLUMN PESSOA.DATA_NASCIMENTO IS
'Data de nascimento da pessoa | CLASSIFICACAO=LGPD_PESSOAL';

COMMENT ON COLUMN PESSOA.SEXO_BIOLOGICO IS
'Sexo biologico informado pela pessoa | CLASSIFICACAO=LGPD_SENSIVEL';

COMMENT ON COLUMN PESSOA.ORIENTACAO_SEXUAL IS
'Orientacao sexual declarada | CLASSIFICACAO=LGPD_SENSIVEL';

COMMENT ON COLUMN PESSOA.IDENTIDADE_GENERO IS
'Identidade de genero declarada | CLASSIFICACAO=LGPD_SENSIVEL';

COMMENT ON COLUMN PESSOA.NOME_SOCIAL IS
'Nome social utilizado pela pessoa | CLASSIFICACAO=LGPD_IDENTIFICAVEL';

COMMENT ON COLUMN PESSOA.ESTADO_CIVIL IS
'Estado civil da pessoa | CLASSIFICACAO=LGPD_PESSOAL';

COMMENT ON COLUMN PESSOA.RENDA_FAMILIAR_MENSAL IS
'Renda familiar mensal declarada | CLASSIFICACAO=LGPD_PESSOAL';

COMMENT ON COLUMN PESSOA.EMAIL IS
'Endereco de email para contato | CLASSIFICACAO=LGPD_IDENTIFICAVEL';

COMMENT ON COLUMN PESSOA.TELEFONE IS
'Telefone para contato | CLASSIFICACAO=LGPD_IDENTIFICAVEL';

COMMENT ON COLUMN ENDERECO.LOGRADOURO IS
'Nome do logradouro | CLASSIFICACAO=LGPD_IDENTIFICAVEL';

COMMENT ON COLUMN ENDERECO.NUMERO IS
'Numero do imovel | CLASSIFICACAO=LGPD_IDENTIFICAVEL';

COMMENT ON COLUMN ENDERECO.COMPLEMENTO IS
'Complemento do endereco | CLASSIFICACAO=LGPD_IDENTIFICAVEL';

COMMENT ON COLUMN ENDERECO.BAIRRO IS
'Bairro do endereco | CLASSIFICACAO=LGPD_PESSOAL';

COMMENT ON COLUMN ENDERECO.CIDADE IS
'Cidade do endereco | CLASSIFICACAO=LGPD_PESSOAL';

COMMENT ON COLUMN ENDERECO.UF IS
'Estado do endereco | CLASSIFICACAO=LGPD_PESSOAL';

COMMENT ON COLUMN ENDERECO.CEP IS
'CEP do endereco | CLASSIFICACAO=LGPD_PESSOAL';

-- ============================================================
-- INDICES
-- ============================================================

CREATE INDEX IDX_PESSOA_CPF
    ON PESSOA (CPF);

CREATE INDEX IDX_PESSOA_NOME
    ON PESSOA (NOME_COMPLETO);

CREATE INDEX IDX_ENDERECO_PESSOA
    ON ENDERECO (ID_PESSOA);

CREATE INDEX IDX_PESSOA_ESCOLARIDADE_PESSOA
    ON PESSOA_ESCOLARIDADE (ID_PESSOA);

CREATE INDEX IDX_PESSOA_FORMACAO_PESSOA
    ON PESSOA_FORMACAO (ID_PESSOA);

CREATE INDEX IDX_PESSOA_PROFISSAO_PESSOA
    ON PESSOA_PROFISSAO (ID_PESSOA);

CREATE INDEX IDX_PESSOA_PROGRAMA_PESSOA
    ON PESSOA_PROGRAMA_SOCIAL (ID_PESSOA);

CREATE INDEX IDX_PESSOA_PROGRAMA_PROGRAMA
    ON PESSOA_PROGRAMA_SOCIAL (ID_PROGRAMA_SOCIAL);